[package]
name = "image_enhancer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "image_enhancer"
path = "src/main.rs"

[dependencies]
image = "0.25"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
