[package]
name = "chonker-tui"
version = "10.0.0"
edition = "2021"
description = "CHONKER v10.0 - CLI-First Document Processing Pipeline"
authors = ["Jack <jack@chonker.ai>"]

[[bin]]
name = "chonker"
path = "src/main.rs"

[features]
default = []
debug = []

[dependencies]
# CLI framework
clap = { version = "4.4", features = ["derive"] }
ratatui = "0.26"
crossterm = "0.27"

# Database and async runtime
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite", "json", "chrono", "uuid"] }
tokio = { version = "1", features = ["full"] }

# Data processing and export
polars = { version = "0.35", features = ["lazy", "json", "parquet", "csv"] }

# Markdown processing
pulldown-cmark = "0.10"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# File system and utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

# Text processing
textwrap = "0.16"
unicode-width = "0.1"
md5 = "0.7"
regex = "1.10"

# Native PDF processing (fast path)
pdfium-render = "0.8"
lopdf = "0.32"
blake3 = "1.5"

# Caching and processing
redis = { version = "0.24", optional = true }
tokio-util = "0.7"
rayon = "1.8"

# PyO3 for Python bridge (optional)
pyo3 = { version = "0.20", features = ["auto-initialize"], optional = true }

[dev-dependencies]
tempfile = "3.0"
