[routing]
# Complexity threshold: <= goes to Rust, > goes to Python
complexity_threshold = 3.0

# Force Python for these file types
force_python_for_types = ["docx", "xlsx", "pptx"]

# Enable fallback from Rust to Python on failure
enable_fallback = true

# Maximum file size for fast path (MB)
max_fast_path_size_mb = 10.0

[processing]
# Number of parallel workers
parallel_workers = 4

# Enable caching
enable_caching = true

# Cache TTL in seconds
cache_ttl_seconds = 3600

[database]
# Enable telemetry collection
enable_telemetry = true

# Auto-vacuum database
auto_vacuum = true
